### PR TITLE
feat: add more fonts

### PR DESCRIPTION
**Pull request by Kiuber**

### CODE REVIEW

**Comment by mingalevme** [comment]
Hi, can you provide some additional info about fonts you choose? Some sites, url?

I migrated from Alpine/Chromium to Debian/GoogleChrome in the **develop** branch, so some problems with font must go away. You can try it with **mingalevme/screenshoter:develop** image.

**Review by mingalevme — COMMENTED** [review]
"afterScreenshotDelay"? But why?

**Comment by mingalevme** [comment]
@Kiuber , and what about extra fonts? May provide examples?

**Review by mingalevme — APPROVED** [review]

**Comment by Kiuber** [comment]
> @Kiuber, "afterScreenshotDelay"? But why?

@mingalevme My idea was that `afterScreenshotDelay` was in place to observe scene where the screenshot is not correct due to some special case. While taking the screenshot, I used `devtoolsFrontendUrl` to observe it. The `afterScreenshotDelay` parameter delays the screenshot after in order to avoid the page closing, which can make it difficult to observe the reasons why the screenshot is not correct. However, the code for `afterScreenshotDelay` was not intended to be merged. Thx!

**Pull request merged**
